/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#030712",
        primary: "#adc6ff",
        secondary: "#4edea3",
        tertiary: "#ffb786",
        'primary-container': "#4d8eff",
        'secondary-container': "#00a572",
        'tertiary-container': "#df7412",
        'surface-container': "#16202e",
        'surface-container-low': "#121c2a",
        'surface-container-lowest': "#050f1c",
        'surface-container-high': "#212b39",
        'surface-container-highest': "#2b3544",
        'surface-variant': "#2b3544",
        'surface-bright': "#303a48",
        'surface-dim': "#091421",
        'on-surface-variant': "#c2c6d6",
        'outline-variant': "#424754",
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        display: ['Outfit', 'sans-serif'],
        space: ['Space Grotesk', 'sans-serif'],
        'display-lg': ['Outfit', 'sans-serif'],
        'headline-md': ['Outfit', 'sans-serif'],
        'label-caps': ['Space Grotesk', 'sans-serif'],
        'metric-lg': ['Space Grotesk', 'sans-serif'],
        'body-base': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'technical-sm': ['Space Grotesk', 'sans-serif'],
        'technical-xs': ['Space Grotesk', 'sans-serif'],
        'data-label': ['Space Grotesk', 'sans-serif'],
        'data-value': ['Space Grotesk', 'sans-serif'],
      },
      spacing: {
        md: "24px",
        "margin-mobile": "16px",
        xs: "8px",
        base: "4px",
        xl: "64px",
        "margin-desktop": "32px",
        gutter: "20px",
        sm: "16px",
        lg: "40px"
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "500" }],
        "metric-lg": ["24px", { lineHeight: "30px", letterSpacing: "0.05em", fontWeight: "700" }],
        "body-base": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "technical-xs": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "technical-sm": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "metric-xl": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "600" }],
      }
    },
  },
  plugins: [],
}
